
spring:
  jackson:
    serialization:
      indent-output: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://service-discovery:8761/eureka}
  instance:
    preferIpAddress: true


